version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    volumes:
      - ./client:/app 

  server:
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "3001:3001" 
    volumes:
      - ./server:/app 

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server